config/routes.rb
Rails.application.routes.draw do
  resources :durations

end

app/models/duration.rb
class Duration < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/durations_controller.rb
class DurationsController < ApplicationController
  before_action :set_duration, only: [:show, :edit, :update, :destroy]

  # GET /durations
  # GET /durations.json
  def index
    @durations = Duration.all
  end

  # GET /durations/1
  # GET /durations/1.json
  def show
  end

  # GET /durations/new
  def new
    @duration = Duration.new
  end

  # GET /durations/1/edit
  def edit
  end

  # POST /durations/request_outgoing_webhook
  # README https://my.slack.com/services/new/outgoing-webhook
  def request_outgoing_webhook
    json_request = JSON.parse(request.body.read)
    parse_outgoing_webhook(json_request["text"])
  end

  # POST /durations
  # POST /durations.json
  def create
    @duration = Duration.new(duration_params)

    respond_to do |format|
      if @duration.save
        format.html { redirect_to @duration, notice: 'Duration was successfully created.' }
        format.json { render :show, status: :created, location: @duration }
      else
        format.html { render :new }
        format.json { render json: @duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /durations/1
  # PATCH/PUT /durations/1.json
  def update
    respond_to do |format|
      if @duration.update(duration_params)
        format.html { redirect_to @duration, notice: 'Duration was successfully updated.' }
        format.json { render :show, status: :ok, location: @duration }
      else
        format.html { render :edit }
        format.json { render json: @duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /durations/1
  # DELETE /durations/1.json
  def destroy
    @duration.destroy
    respond_to do |format|
      format.html { redirect_to durations_url, notice: 'Duration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duration
      @duration = Duration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duration_params
      params.require(:duration).permit(:unique_id, :category, :account_name, :started_at, :ended_at, :minutes)
    end

    def parse_outgoing_webhook(text)
      # text.match(/\<https:\/\/app\.wercker\.com\/\#build\/(.+?)\|.*\sof\s(.+?)\sby\s(.+?)\spassed/)
      # text.match(/[wantedly:production] awakia invoked 'deploy'/)
      # text.match(/^\[wantedly:production\].*invoked\s'deploy:unlock'/)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/durations_helper.rb
module DurationsHelper
end

app/views/durations/_form.html.erb
<%= form_for(@duration) do |f| %>
  <% if @duration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duration.errors.count, "error") %> prohibited this duration from being saved:</h2>

      <ul>
      <% @duration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unique_id %><br>
    <%= f.text_field :unique_id %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :account_name %><br>
    <%= f.text_field :account_name %>
  </div>
  <div class="field">
    <%= f.label :started_at %><br>
    <%= f.datetime_select :started_at %>
  </div>
  <div class="field">
    <%= f.label :ended_at %><br>
    <%= f.datetime_select :ended_at %>
  </div>
  <div class="field">
    <%= f.label :minutes %><br>
    <%= f.number_field :minutes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/durations/edit.html.erb
<h1>Editing Duration</h1>

<%= render 'form' %>

<%= link_to 'Show', @duration %> |
<%= link_to 'Back', durations_path %>

app/views/durations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Durations</h1>

<table>
  <thead>
    <tr>
      <th>Unique</th>
      <th>Category</th>
      <th>Account name</th>
      <th>Started at</th>
      <th>Ended at</th>
      <th>Minutes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @durations.each do |duration| %>
      <tr>
        <td><%= duration.unique_id %></td>
        <td><%= duration.category %></td>
        <td><%= duration.account_name %></td>
        <td><%= duration.started_at %></td>
        <td><%= duration.ended_at %></td>
        <td><%= duration.minutes %></td>
        <td><%= link_to 'Show', duration %></td>
        <td><%= link_to 'Edit', edit_duration_path(duration) %></td>
        <td><%= link_to 'Destroy', duration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Duration', new_duration_path %>

app/views/durations/new.html.erb
<h1>New Duration</h1>

<%= render 'form' %>

<%= link_to 'Back', durations_path %>

app/views/durations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unique:</strong>
  <%= @duration.unique_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @duration.category %>
</p>

<p>
  <strong>Account name:</strong>
  <%= @duration.account_name %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @duration.started_at %>
</p>

<p>
  <strong>Ended at:</strong>
  <%= @duration.ended_at %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @duration.minutes %>
</p>

<%= link_to 'Edit', edit_duration_path(@duration) %> |
<%= link_to 'Back', durations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DurationServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>